version: "3.8"
services:
  api:
    build: ./api/
    container_name: api_container
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app/api # syncs the api folder with the container
      - api_node_modules:/app/api/node_modules
    networks:
      - app-network
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db # syncs the data folder with the container
    networks:
      - app-network

  ui:
    build: ./ui/
    container_name: ui_container
    ports:
      - "3000:5173"

    volumes:
      - ./ui:/app/ui # syncs the ui folder with the container
      - ui_node_modules:/app/ui/node_modules
    networks:
      - app-network
    depends_on:
      - api
networks:
  app-network:
    driver: bridge
volumes:
  data:
  api_node_modules:
  ui_node_modules:
